#!/usr/bin/env bash
# git-tag-release.sh
# Creates a git commit and annotated tag for the release.
# Usage: bash git-tag-release.sh <version> [release-notes-path]
# NOTE: Does NOT push — user decides when to push.

set -e

VERSION="${1}"
RELEASE_NOTES="${2:-RELEASE-NOTES.md}"

if [ -z "$VERSION" ]; then
    echo "[ERROR] Version is required."
    echo "Usage: bash git-tag-release.sh <version> [release-notes-path]"
    exit 1
fi

TAG="v${VERSION}"

echo "=== Git Release Tagger ==="
echo "Version: $VERSION"
echo "Tag:     $TAG"
echo ""

# --- Verify git repo ---
if [ ! -d ".git" ]; then
    echo "[ERROR] Not a git repository. Initialize git first."
    exit 1
fi

# --- Check for uncommitted changes ---
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "[INFO] Uncommitted changes detected. Staging release files..."
fi

# --- Stage release artifacts ---
FILES_TO_STAGE=(
    "CHANGELOG.md"
    "RELEASE-NOTES.md"
    "VERSION"
)

# Also stage version files if they exist
[ -f "package.json" ]    && FILES_TO_STAGE+=("package.json")
[ -f "pyproject.toml" ]  && FILES_TO_STAGE+=("pyproject.toml")
[ -f "Cargo.toml" ]      && FILES_TO_STAGE+=("Cargo.toml")

for f in "${FILES_TO_STAGE[@]}"; do
    if [ -f "$f" ]; then
        git add "$f"
        echo "[STAGED] $f"
    fi
done

# Stage docs/release/ if it exists
if [ -d "docs/release" ]; then
    git add docs/release/
    echo "[STAGED] docs/release/"
fi

# --- Commit ---
COMMIT_MSG="release: v${VERSION}

Generated by Release Skill.
See RELEASE-NOTES.md for details."

git commit -m "$COMMIT_MSG" 2>&1 || echo "[INFO] Nothing new to commit."

# --- Create annotated tag ---
TAG_MESSAGE="Release v${VERSION}"
if [ -f "$RELEASE_NOTES" ]; then
    # Use first 20 lines of release notes as tag message
    TAG_MESSAGE=$(head -20 "$RELEASE_NOTES")
fi

# Check if tag already exists
if git rev-parse "$TAG" >/dev/null 2>&1; then
    echo "[WARN] Tag $TAG already exists."
    echo "To overwrite: git tag -d $TAG && git tag -a $TAG -m 'Release $VERSION'"
else
    git tag -a "$TAG" -m "$TAG_MESSAGE"
    echo "[OK] Tag created: $TAG"
fi

echo ""
echo "=== Next Steps ==="
echo "To push this release to remote:"
echo "  git push origin main"
echo "  git push origin $TAG"
echo ""
echo "Or push all at once:"
echo "  git push && git push --tags"
